document:
  name: DigComp2.1 - Il quadro di riferimento per le competenze digitali dei cittadini
  description: |
    Il quadro di riferimento per le competenze digitali dei cittadini europei,
    noto anche come DigComp, rappresenta uno strumento per migliorare le
    competenze digitali dei cittadini sia nelle attività quotidiane che
    lavorative, definendo conoscenze minime suddivise in livelli che vanno dalla
    conoscenza dell’uso di base della rete alla competenza di intervento in caso
    di problemi di privacy e sicurezza informatica. AGID è la prima realtà
    governativa in Europa a curare ufficialmente e direttamente la traduzione e
    la promozione del modello DigComp2.1.
  tags:
    - competenze digitali
    - linee guida